version: "3"
services:
    postgres:
        image: postgres:9.6
        container_name: postgres
        volumes: 
            - ./airflow/script/dbinit:/docker-entrypoint-initdb.d
            - ./database-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: airflow
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD:
            GTFS_DB: gtfs
            GTFS_DB_USER:
            GTFS_DB_PASSWORD:
            FERNET_KEY:
        ports:
            - 5432:5432
    airflow:
        image: mapohl/airflow:latest
        container_name: airflow
        restart: always
        depends_on:
            - postgres
        environment:
            POSTGRES_HOST: postgres
            LOAD_EX: n
            EXECUTOR: Local
            GTFS_DB_USER:
            GTFS_DB_PASSWORD:
            FERNET_KEY:
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./airflow/plugins:/usr/local/airflow/plugins
            - ./pipeline-data:/usr/local/data/
        ports:
            - 8080:8080
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - postgres
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.156.0.5
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: gtfs-arrivals:1:1
