version: '2.1'
services:
    postgres_airflow:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
    postgres_app:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=app_user
            - POSTGRES_PASSWORD=app_user
            - POSTGRES_DB=vbb_database
        ports:
            - "5433:5432"
    webserver:
        image: mapohl/airflow:latest
        restart: always
        depends_on:
            - postgres_airflow
            - postgres_app
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
            - ./pipeline-data:/usr/local/data/
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
